package com.example.vault.storageoption;

public class StorageOptionsCommon {
    public static String APP_PATHNAME = "nsvault/";
    public static String AUDIOS = null;
    public static String AUDIOS_DEFAULT_ALBUM = "My Playlist";
    public static String AUDIOS_TEMP_FOLDER = null;
    public static String DOCUMENTS = null;
    public static String DOCUMENTS_DEFAULT_ALBUM = "My Documents";
    public static String ENTRY = "Entry_";
    public static boolean IsAllDataMoveingInProg = false;
    public static boolean IsAllDataRecoveryInProg = false;
    public static boolean IsApphasDataforTransfer = false;
    public static boolean IsDeviceHaveMoreThenOneStorage = false;
    public static boolean IsStorageSDCard = false;
    public static boolean IsUserHasDataToRecover = false;
    public static int Kitkat = 19;
    public static String NOTES = null;
    public static String NOTES_FILE_EXTENSION = ".dat";
    public static String PHOTOS = null;
    public static String PHOTOS_DEFAULT_ALBUM = "My Photos";
    public static String STORAGE = "Calculator Vault/";
    public static String STORAGEPATH = "";
    public static String STORAGEPATH_1 = "";
    public static String STORAGEPATH_2 = "";
    public static String TEMPFILES;
    public static String TODOLIST;
    public static String VIDEOS;
    public static String VIDEOS_DEFAULT_ALBUM = "My Videos";
    public static String WALLET;
    public static String WALLET_ENTRY_FILE_EXTENSION = ".dat";

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(STORAGE);
        sb.append(APP_PATHNAME);
        sb.append("Photos/");
        PHOTOS = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(STORAGE);
        sb2.append(APP_PATHNAME);
        sb2.append("Videos/");
        VIDEOS = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append(STORAGE);
        sb3.append(APP_PATHNAME);
        sb3.append("TempFiles/");
        TEMPFILES = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append(STORAGE);
        sb4.append(APP_PATHNAME);
        sb4.append("Documents/");
        DOCUMENTS = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append(STORAGE);
        sb5.append(APP_PATHNAME);
        sb5.append("Wallet/");
        WALLET = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append(STORAGE);
        sb6.append(APP_PATHNAME);
        sb6.append("Notes/");
        NOTES = sb6.toString();
        StringBuilder sb7 = new StringBuilder();
        sb7.append(STORAGE);
        sb7.append(APP_PATHNAME);
        sb7.append("PlayLists/FLCipherTemp/");
        AUDIOS_TEMP_FOLDER = sb7.toString();
        StringBuilder sb8 = new StringBuilder();
        sb8.append(STORAGE);
        sb8.append(APP_PATHNAME);
        sb8.append("ToDoLists/");
        TODOLIST = sb8.toString();
        StringBuilder sb9 = new StringBuilder();
        sb9.append(STORAGE);
        sb9.append(APP_PATHNAME);
        sb9.append("PlayLists/");
        AUDIOS = sb9.toString();
    }
}
